### ISSUE TITLE
Webpack 的思维导图 的preview不够清晰

### ISSUE THREAD

**Issue by SLRXXX** [zhangwang1990/blogs#1]
RT，只是想在线直观地看一下，省掉本地下载导入的麻烦

**Comment by xian107** [comment]
运行出错是怎么回事？
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:dev' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild:dev', 'build:dev', 'postbuild:dev' ]
5 info prebuild:dev rock_cms@1.0.0
6 info build:dev rock_cms@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info rock_cms@1.0.0 Failed to exec build:dev script
9 verbose stack Error: rock_cms@1.0.0 build:dev: `webpack --progress --colors --watch --config webpack.dev.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid rock_cms@1.0.0
11 verbose cwd E:\nn
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error rock_cms@1.0.0 build:dev: `webpack --progress --colors --watch --config webpack.dev.js`
17 error Exit status 1
18 error Failed at the rock_cms@1.0.0 build:dev script 'webpack --progress --colors --watch --config webpack.dev.js'.
18 error This is most likely a problem with the rock_cms package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack --progress --colors --watch --config webpack.dev.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs rock_cms
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls rock_cms
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
