### ISSUE TITLE
运行出错请问怎么回事？

### ISSUE THREAD

**Issue by xian107** [zhangwang1990/blogs#2]
运行下面三个怎么都出错啊？这是怎么回事

E:\nn>npm run build:dev

> rock_cms@1.0.0 build:dev E:\nn
> webpack --progress --colors --watch --config webpack.dev.js

E:\nn\webpack.dev.js:1
(function (exports, require, module, __filename, __dirname) { let webpack = requ
ire("webpack");
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (E:\nn\node_modules\webpack\bin\convert-argv.js:97:18)
    at E:\nn\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (native)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! rock_cms@1.0.0 build:dev: `webpack --progress --colors --watch --config
 webpack.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rock_cms@1.0.0 build:dev script 'webpack --progress --col
ors --watch --config webpack.dev.js'.
npm ERR! This is most likely a problem with the rock_cms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors --watch --config webpack.dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rock_cms
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls rock_cms
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nn\npm-debug.log

**Comment by Val-Zhang** [comment]
@xian107 你的node是v4.5.0？可能是node版本过低，不支持一些es6的语法。
