### ISSUE TITLE
生成开发环境代码时，文件名undefined

### ISSUE THREAD

**Issue by RationalPoet** [zhangwang1990/blogs#3]
![qq 20171025105220](https://user-images.githubusercontent.com/18318555/31978165-9e30a0f8-b972-11e7-9bc1-3f9bead67338.png)

**Comment by Val-Zhang** [comment]
应该是window和MacOS系统对路径的处理不同，windows下路径应该使用`\`，而MacOS下应该使用`/`,用的MacOS系统，之前没考虑windows下的这个问题，之后找一个windows的电脑后，我再修改一下这里的代码

**Comment by autumnup** [comment]
请问需要怎么配置呢

**Comment by autumnup** [comment]
@zhangwang1990 请问一下 生成文件名为undefined  需要如何配置呢  求教
