### ISSUE TITLE
vue脚手架生成的项目中使用

### ISSUE THREAD

**Issue by tonyjiafan** [zhangwang1990/blogs#5]
集成到vue脚手架生成的项目中使用的话，应改怎么去配置，给我一个思路！是直接去修改webpack的配置吗？

**Comment by Val-Zhang** [comment]
我没怎么使用vue，不过React脚手架（`create-react-app`）集成了`webpack`,在命令行中使用`npm run eject`可以生成对应的`webpack`配置文件，可以在其中进行进一步的配置。

**Comment by tonyjiafan** [comment]
感谢！ 我想问下这个项目中的你cat和dog路由在哪里配置的？

**Comment by Val-Zhang** [comment]
这里的cat,dog等其实都是单独的页面，所以其实并没有在前端配置路由，实际应该由后端路由来控制，在这个demo里面使用了`webpack`做本地服务器做代理。
    
```js
devServer.historyApiFallback.rewrites.push(
        {from: `${fileName}`, to: `/dist/${fileName}.html`}
```

**Comment by tonyjiafan** [comment]
QQQ
